copy theme.xml ..\3do
copy theme.xml ..\amiga
copy theme.xml ..\amigacd32
copy theme.xml ..\amstradcpc
copy theme.xml ..\apple2
copy theme.xml ..\arcade
copy theme.xml ..\atari
copy theme.xml ..\atari2600
copy theme.xml ..\atari5200
copy theme.xml ..\atari7800
copy theme.xml ..\atari800
copy theme.xml ..\atarijaguar
copy theme.xml ..\atarilynx
copy theme.xml ..\atarist
copy theme.xml ..\auto-allgames
copy theme.xml ..\auto-favorites
copy theme.xml ..\auto-lastplayed
copy theme.xml ..\batman
copy theme.xml ..\c64
copy theme.xml ..\capcom
copy theme.xml ..\castlevania
copy theme.xml ..\colecovision
copy theme.xml ..\cps1
copy theme.xml ..\cps2
copy theme.xml ..\cps3
copy theme.xml ..\custom-collections
copy theme.xml ..\daphne
copy theme.xml ..\dataeast
copy theme.xml ..\disney
copy theme.xml ..\donkeykong
copy theme.xml ..\dreamcast
copy theme.xml ..\famicom
copy theme.xml ..\fba
copy theme.xml ..\fds
copy theme.xml ..\finalfantasy
copy theme.xml ..\frogger
copy theme.xml ..\gameandwatch
copy theme.xml ..\gamegear
copy theme.xml ..\gb
copy theme.xml ..\gba
copy theme.xml ..\gbc
copy theme.xml ..\gc
copy theme.xml ..\genesis
copy theme.xml ..\intellivision
copy theme.xml ..\irem
copy theme.xml ..\kodi
copy theme.xml ..\kof
copy theme.xml ..\konami
copy theme.xml ..\mame
copy theme.xml ..\mario
copy theme.xml ..\mastersystem
copy theme.xml ..\megacd
copy theme.xml ..\megadrive
copy theme.xml ..\megadrive-japan
copy theme.xml ..\megaman
copy theme.xml ..\midway
copy theme.xml ..\mortalkombat
copy theme.xml ..\msx
copy theme.xml ..\msx2
copy theme.xml ..\n64
copy theme.xml ..\namco
copy theme.xml ..\nds
copy theme.xml ..\neogeo
copy theme.xml ..\nes
copy theme.xml ..\ngp
copy theme.xml ..\ngpc
copy theme.xml ..\nintendo
copy theme.xml ..\odyssey2
copy theme.xml ..\oric
copy theme.xml ..\pacman
copy theme.xml ..\pc
copy theme.xml ..\pce-cd
copy theme.xml ..\pcengine
copy theme.xml ..\pcenginecd
copy theme.xml ..\pixel
copy theme.xml ..\ports
copy theme.xml ..\psp
copy theme.xml ..\pspminis
copy theme.xml ..\psx
copy theme.xml ..\residualvm
copy theme.xml ..\retropie
copy theme.xml ..\saturn
copy theme.xml ..\scummvm
copy theme.xml ..\sega
copy theme.xml ..\sega32x
copy theme.xml ..\segacd
copy theme.xml ..\sfc
copy theme.xml ..\sg-1000
copy theme.xml ..\sgfx
copy theme.xml ..\shmups
copy theme.xml ..\snes
copy theme.xml ..\snk
copy theme.xml ..\sonic
copy theme.xml ..\starwars
copy theme.xml ..\steam
copy theme.xml ..\streetfighter
copy theme.xml ..\supergrafx
copy theme.xml ..\taito
copy theme.xml ..\tg16
copy theme.xml ..\tg16cd
copy theme.xml ..\ti99
copy theme.xml ..\tmnt
copy theme.xml ..\vectrex
copy theme.xml ..\vic20
copy theme.xml ..\videopac
copy theme.xml ..\virtualboy
copy theme.xml ..\wii
copy theme.xml ..\wiiu
copy theme.xml ..\williams
copy theme.xml ..\wonderswan
copy theme.xml ..\wonderswancolor
copy theme.xml ..\zelda
copy theme.xml ..\zmachine
copy theme.xml ..\zxspectrum